services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=com.mysql.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - db
  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local
